# Generated by Django 4.0.4 on 2022-11-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_status_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_statment',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
