# Generated by Django 4.0.4 on 2022-11-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_vendor_statment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='stock',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
