# Generated by Django 4.0.4 on 2022-11-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_itemtable_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_expense',
            name='destinofsupply',
        ),
        migrations.RemoveField(
            model_name='purchase_expense',
            name='gsttype',
        ),
    ]
