# Generated by Django 4.0.4 on 2022-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_item_stock_bitm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill_item',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit1',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
