# Generated by Django 4.0.4 on 2022-11-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_purchasebill_item_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='itmdate',
            field=models.DateField(null=True),
        ),
    ]
