# Generated by Django 4.0.4 on 2022-11-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_itemtable_itmdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill_item',
            name='itmdt',
            field=models.DateField(null=True),
        ),
    ]
