# Generated by Django 4.0.4 on 2022-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_purchasebill_item_itmdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
