# Generated by Django 4.0.4 on 2022-11-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_expense2_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill_item',
            name='itmdt',
        ),
    ]
