# Generated by Django 4.0.2 on 2022-12-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_salescreditnote_salescreditnote1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salescreditnote',
            old_name='debit_no',
            new_name='credit_no',
        ),
        migrations.RenameField(
            model_name='salescreditnote',
            old_name='debitdate',
            new_name='creditdate',
        ),
    ]
