# Generated by Django 4.0.2 on 2022-12-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_banking_payment_accounts1id_banking_payment_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking_payment',
            name='pym_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
