# Generated by Django 4.0.2 on 2022-12-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_banking_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking_payment',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
